x<-read.csv("D:/Lecture Stuff/regression_75.csv")
x
summary(x)
sapply(x,sd)
x$Study_mat<-factor(x$Study_mat)
x$faculty_rating<-factor(x$faculty_rating)
x$Competitive<-factor(x$Competitive)
x$Category<-factor(x$Category)
x$Mode<-factor(x$Mode)
set.seed(12345)

split = sample.split(x$Clear, SplitRatio = 0.70)
train<-subset(x,split==TRUE)

exp(coef(a1))
a211<-glm(x$Clear~.,data=x,family='binomial')
summary(a211)
library(ggplot2)
predicted= predict(a1, newdata=x, type="response")
plot(predicted~x$Hours+x$Category+x$Study_mat+x$faculty_rating+x$Competitive)
a2<-glm(x$Clear~x$Hours+x$Category+x$Study_mat+x$faculty_rating+x$Competitive,family='binomial',data=x)
summary(a2)
library(caTools)
test<-subset(x,split==FALSE)
dim(train)
dim(test)
aa<-glm(x$Clear~x$Hours+x$Category+x$Study_mat+x$faculty_rating+x$Competitive,family='binomial',data=train)
summary(aa)
predTrain<-predict(aa,newdata=train,type="response")
predTest <- predict(aa,type="response")
library(caret)
summary(predTest)
summary(predTrain)
table(as.factor(ifelse(predTrain>0.5, 'yes', 'no')), train$Clear)
caret::confusionMatrix(data=as.numeric(predTrain>0.5),reference=train$Clear)
install.packages('e1071', dependencies=TRUE)
